### ISSUE TITLE
load_model_and_alphabet_local model_name not defined

### ISSUE THREAD

**Issue by eric-tc-wong** [facebookresearch/esm#101]
Hello,

Thank you for making these wonderful models available, and congratulations on the new publication.
The new update broke the code for loading local models.

**Bug description**

At load_model_and_alphabet_local, "model_name" is not defined.

**Reproduction steps**

model_dir = prepend_dir + './esm1b_t33_650M_UR50S.pt'
model, alphabet = esm.pretrained.load_model_and_alphabet_local(model_dir)

**Logs**

```
/usr/local/lib/python3.7/dist-packages/esm/pretrained.py in load_model_and_alphabet_local(model_location)
     55     """ Load from local path. The regression weights need to be co-located """
     56     model_data = torch.load(model_location, map_location='cpu')
---> 57     if _has_regression_weights(model_name):
     58         regression_location = model_location[:-3] + "-contact-regression.pt"
     59         regression_data = torch.load(regression_location, map_location='cpu')

NameError: name 'model_name' is not defined
```

**Comment by tomsercu** [comment]
Thanks @eric-tc-wong for reporting this oversight!

**Comment by eric-tc-wong** [comment]
Hi Tom,

Thank you for fixing this so quickly. I am glad to be of help.

Best,
Eric
