### ISSUE TITLE
What model is needed for regression_data in esm.pretrained.load_model_and_alphabet_local？

### ISSUE THREAD

**Issue by xmhh** [facebookresearch/esm#103]
**Bug description**
Use esm.pretrained.load_model_and_alphabet_local(
                     'esm1_t12_85M_UR50S.pt'), i need to load esm1_t12_85M_UR50S-contact-regression.pt, but in fact this is not provided.

**Logs**
![image](https://user-images.githubusercontent.com/42038757/125476753-d2183b4d-3217-48d5-a347-52fcb65eeefa.png)

```
Output goes here
```

**Additional context**
If you want to load the local esm model, besides the esm1_t12_85M_UR50S.pt you provided, do you need any regression model? What is the meaning of regression_data in your code esm.pretrained.load_model_and_alphabet_local
.

**Comment by xmhh** [comment]
The 0.3.1 version uses the try except statement, so there is no regression-related model in the load and no error will be reported, but I still want to know what this regression does?

**Comment by tomsercu** [comment]
Yes you need a second file to load the regression weights, aka weights of the ContactPredictionHead.
Failure was silent before, but better to be explicit.
If you load via `esm.pretrained.esm1_t12_85M_UR50S()`, the regression weights will be downloaded to `~/.cache/torch/hub/checkpoints`. 
Let me know if that helps?

**Comment by xmhh** [comment]
> Yes you need a second file to load the regression weights, aka weights of the ContactPredictionHead.
> Failure was silent before, but better to be explicit.
> If you load via `esm.pretrained.esm1_t12_85M_UR50S()`, the regression weights will be downloaded to `~/.cache/torch/hub/checkpoints`.
> Let me know if that helps?
Yes, what you said is a useful solution. If I don’t want to download this model from `https://dl.fbaipublicfiles.com/fair-esm/regression`, can you provide it directly like other training models? just like download link below.
![image](https://user-images.githubusercontent.com/42038757/125540752-a43f4622-2d84-4d2e-94fe-b6f3253a0e1c.png)

 Of course, we can also know his address from your source code, but it may be slightly inconvenient.
Thanks for you reply. : )

**Comment by tomsercu** [comment]
Ah yes - we should update that table with link to both model weights and regression. 
For now: [This is the code](https://github.com/facebookresearch/esm/blob/master/esm/pretrained.py#L43) which points to 
`https://dl.fbaipublicfiles.com/fair-esm/regression/{model_name}-contact-regression.pt`

**Comment by tomsercu** [comment]
@xmhh is your problem solved?

**Comment by Mountain-White** [comment]
Sry for bothering，but I can‘t run your esm-1v code for losing contact-regression.pt.  I try to download from pretrained:load_regression_hub(), but failed again.However, I can download esm-1b.Did you forget to upload or ...?

**Comment by tomsercu** [comment]
@Mountain-White `esm-1v` does not have contact-regression.pt because it is not optimal for that task (rather it is best for variant prediction). Does that answer your question?

**Comment by Mountain-White** [comment]
> @Mountain-White `esm-1v` does not have contact-regression.pt because it is not optimal for that task (rather it is best for variant prediction). Does that answer your question?

still bugs……
![1627959656(1)](https://user-images.githubusercontent.com/53006885/127950848-74b4e58c-3bf1-4f98-b134-d4d9454f12f8.png)
 Maybe caused by the torch version, I am checking on it

**Comment by Mountain-White** [comment]
> @Mountain-White `esm-1v` does not have contact-regression.pt because it is not optimal for that task (rather it is best for variant prediction). Does that answer your question?

thx ,the problem is solved.
