### ISSUE TITLE
HTTP Error 403: Forbidden: "esm1v_t33_650M_UR90S_1-contact-regression.pt"

### ISSUE THREAD

**Issue by Licko0909** [facebookresearch/esm#108]
**Bug description**
Halo~, Dear developer. 
I cannot download this file, "esm1v_t33_650M_UR90S_1-contact-regression.pt", log like the following:
![image](https://user-images.githubusercontent.com/27897166/125771130-5b4d29eb-598c-4b13-a65f-209b40439064.png)

**Code**
python variant-prediction/predict.py \
    --model-location esm1v_t33_650M_UR90S_1 esm1v_t33_650M_UR90S_2 esm1v_t33_650M_UR90S_3 esm1v_t33_650M_UR90S_4 esm1v_t33_650M_UR90S_5 \
    --sequence HPETLVKVKDAEDQLGARVGYIELDLNSGKILESFRPEERFPMMSTFKVLLCGAVLSRVDAGQEQLGRRIHYSQNDLVEYSPVTEKHLTDGMTVRELCSAAITMSDNTAANLLLTTIGGPKELTAFLHNMGDHVTRLDRWEPELNEAIPNDERDTTMPAAMATTLRKLLTGELLTLASRQQLIDWMEADKVAGPLLRSALPAGWFIADKSGAGERGSRGIIAALGPDGKPSRIVVIYTTGSQATMDERNRQIAEIGASLIKHW \
    --dms-input ./variant-prediction/examples/BLAT_ECOLX_Ranganathan2015.csv \
    --mutation-col mutant \
    --dms-output ./variant-prediction/examples/BLAT_ECOLX_Ranganathan2015_labeled.csv \
    --offset-idx 24 \
    --scoring-strategy wt-marginals

**Comment by tomsercu** [comment]
Seems like a version issue; can you update the installed `esm` to the latest version?
The regression weights do not exist for the `esm-1v` models, but the logic around silently ignoring these failures changed.

**Comment by Licko0909** [comment]
Thanks you! Problem solved!

**Comment by tomsercu** [comment]
Great! closing this issue
