### ISSUE TITLE
Difference between different ESM1v models?

### ISSUE THREAD

**Issue by xinformatics** [facebookresearch/esm#111]
Hi, I am trying to compare ESM1b vs ESM1v embeddings for downstream prediction tasks? I observe that the ESM1v model has 5 variants such as esm1v_t33_650M_UR90S_1, esm1v_t33_650M_UR90S_2 etc.. Could you please tell how these models are different?
Thanks

**Comment by tomsercu** [comment]
Hi, they're using different random seeds. We use them to ensemble predictions.

**Comment by xinformatics** [comment]
Do you expect that the embeddings from models trained with different seeds to be significantly different from each other?

**Comment by tomsercu** [comment]
Yes the embeddings will be very different, since the random initialization will send them in a totally different direction.
But the LM probabilities will usually be rather close.

**Comment by xinformatics** [comment]
Thank you so much for the help.

**Comment by ptynecki** [comment]
@xinformatics how are you planning to test ESM1v embeddings in your downstream prediction tasks? By averaging the vectors from all the models into the one?

**Comment by xinformatics** [comment]
@ptynecki I am not using ESM1 and ESM1b. I am working with only the mean embeddings obtained from ESM1v. My downstream task is multi-input multi-output so I can't really fine tune the model and hence I have to use the embeddings.
