### ISSUE TITLE
Model fine tuning example

### ISSUE THREAD

**Issue by wjs20** [facebookresearch/esm#12]
Hi, 

Thanks for making the model public! I would like to fine-tune the model for a downstream task, however in your colab model you only make inference using the pre-trained model, without any fine tuning it seems. Could you advise me on the best way to go about finetuning with this model? provide an example script? 

Thanks so much.

**Comment by joshim5** [comment]
Hi @wjs20, thanks for your interest! Yes, the ESM model is a subclass of `nn.Module`, so you can just use it as a component inside another torch model. We don't provide any examples fine-tuning the model, but there are many generic pytorch tutorials that can show how to do this, [for example this one](https://huggingface.co/transformers/training.html) from Huggingface.

Hope this helps! I'm closing out the issue, but please let us know if you have any additional questions.

**Comment by wjs20** [comment]
Thanks for the advice joshin5. I will have a go!
