### ISSUE TITLE
retrain esm

### ISSUE THREAD

**Issue by poppy-yebo** [facebookresearch/esm#137]
I just want to know how to  only use my  sequence to train this model.thank you very much

**Comment by shikhar249** [comment]
Hi Tom, 

How large should the sequence database be for retraining the model ? I have a sequence database consisting around 3000 sequence.

**Comment by tomsercu** [comment]
For pretraining you'd typically want to use very large sequence databases, since the language model of this size would easily memorize smaller datasets. In the case of 3000 sequences, you'd typically want to finetune a pre-trained language model.
