### ISSUE TITLE
decode method for batch_converter

### ISSUE THREAD

**Issue by wjs20** [facebookresearch/esm#14]
Hi 

I have been working with some of the models from the hugging face library and their tokenizers have a .decode() method associated with them. it seems that 'batch_converter' is the esm equivelent of huggingfaces 'tokenizer', but I can't find a similar method to map back from ids to strings. Is there one? 

Thanks

**Comment by joshim5** [comment]
Hi @wjs20: Yes, you can do this with ESM. Given an `alphabet: Alphabet` and a list of token ids `token_ids: List[int]`, you can recover the corresponding string with `''.join(alphabet.get_tok(i) for i in token_ids)`. 

Hope this helps!
