### ISSUE TITLE
Huggingface Transformers model compatibility?

### ISSUE THREAD

**Issue by ddofer** [facebookresearch/esm#152]
Is there any way to directly load the ESM models with the HF Transformers (or similarly compatible) libraries? e.g. with `AutoModelForTokenClassification`?
 Thanks!

(I want to do finetuning, and to use additional libraries that support the HF models' format).

**Comment by tomsercu** [comment]
Very happy to share that - thanks to the amazing work of @Rocketknight1 and team - this is now possible:

> Classification tasks with proteins, just like BERT: https://colab.research.google.com/github/huggingface/notebooks/blob/main/examples/protein_language_modeling.ipynb
> 
> Fold proteins in Colab or your local GPU and export PDB files: https://colab.research.google.com/github/huggingface/notebooks/blob/main/examples/protein_folding.ipynb

**Comment by Admire7494** [comment]
Is that work? I found that it's difficult to load ESM1b_650M with half precision in a RTX3090
