### ISSUE TITLE
KeyError: 'J'

### ISSUE THREAD

**Issue by liudan111** [facebookresearch/esm#164]
code:

python extract.py esm1_t34_670M_UR50S run.fasta AB644285 --repr_layers 34 --include mean

**Bug description**
Traceback (most recent call last):
  File "extract.py", line 136, in <module>
    main(args)
  File "extract.py", line 83, in main
    for batch_idx, (labels, strs, toks) in enumerate(data_loader):
  File "/home1/*/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home1/*/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 475, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home1/*/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home1/*/tool/esm/esm/data.py", line 258, in __call__
    seq_encoded_list = [self.alphabet.encode(seq_str) for seq_str in seq_str_list]
  File "/home1/*/tool/esm/esm/data.py", line 258, in <listcomp>
    seq_encoded_list = [self.alphabet.encode(seq_str) for seq_str in seq_str_list]
  File "/home1/*/tool/esm/esm/data.py", line 243, in encode
    return [self.tok_to_idx[tok] for tok in self.tokenize(text)]
  File "/home1/*/tool/esm/esm/data.py", line 243, in <listcomp>
    return [self.tok_to_idx[tok] for tok in self.tokenize(text)]
KeyError: 'J'

When I input a protein sequence like:

>BAL03319.1|/gene="P",/product="polymerase"||AB644285|join{[2258:3164](+), [0:1575](+)}
MPLSYQHFRKLLLLDDEAGPLEEELPRLADEGLNRRVAEDLNLGNPNVSIPWTHKVGNFT
GLYSSTVPVFNPEWQTPSFPDIHLREDIIDRCQQYVGPLTVNEKRRLKLIMPARFYPNFT
KYMPLDKGIKPYYPEHAVNHYFKTRHYLHTLWKAGILYKRETTRSASFFGSPYSWEQDLH
HGAFVDGPSRVGKESFYQQSSGVLSRPPVGSRIPRKFQQSRLGFQSQQGSLASGKSGRSG
SIRARVHPTTRRSVGVEPASSGHIDNSASSASSCLHQSAVRKTAYSHLSTSKRQSSSGHA
VELHPCWWLQFRNSKPCSDYCLSHIVNLLEDWEPCIEHGEHNIRIPRTPARVTGGVFLVD
KNPHNTTESRLVVDFSQFSRGSTRVSWPKFAVPNLQSLTNLLSSNLSWLSLDVSAAFYHL
PLHPAAMPHLLVGSSGLPRYVARLSSTSRNINHQHGTMQDLHDSCSRNLYVSLMLLYKTF
GWKLHLYSHPIILGFRKIPMGVGLSPFLLAQFTSAICSVVRRAFPHCLAFSYMDDLVLGA
KSVQHLESLYATITNFLLSLGIHLNPNKTKRWGYSLNFMGYVIGSWGTLPQEHIVLKJKQ
CFRKLPVNRPIDWKVCQRIVGLLGFAAPFTQCGYPALMPLYACIHAKQAFTFSPTYKAFL
CKQYLNLYPVARQRSGLCQVFADATPTGWGLAIGHQRMRGTFVAPLPIHTAELLAACFAR
SRSGAKLIGTDNSVVLSRKYTSFPWLLGCAANWILRGTSFVYVPSALNPADDPSRGRLGI
YRPLLRLPFRPTTGRTSLYAVSPSVPSHLPDRVHFASPLHVAWRPP

why there is an issue like this?  I would be appreciated that if you could help me.

**Comment by MesihK** [comment]
J is an ambiguous amino acid that is I assume ESM not trained for.

**Comment by liudan111** [comment]
> J is an ambiguous amino acid that is I assume ESM not trained for.

Thank you for your reply!  you are right, I try to run several protein sequences including J, the errors are all  "KeyError: 'J'"

**Comment by tomsercu** [comment]
Thanks @MesihK  - Correct, esm is trained on the 20 standard amino acids plus some ambiguous amino acids like X, B, Z, etc, if they appear in uniref-50.
See https://github.com/facebookresearch/esm/blob/main/esm/constants.py#L8

**Comment by zhoubay** [comment]
Same Error here, but my interest is why uniref50 treat `J` so differently. I mean, X, B, J and Z are all ambiguous amino acids. From [wiki](https://en.wikipedia.org/wiki/Proteinogenic_amino_acid), `B` indicates [Asparagine](https://en.wikipedia.org/wiki/Asparagine) or [aspartic acid](https://en.wikipedia.org/wiki/Aspartic_acid), `J` indicates [Leucine](https://en.wikipedia.org/wiki/Leucine) or [isoleucine](https://en.wikipedia.org/wiki/Isoleucine), `X` stands for Unknown and `Z` stands for [Glutamic acid](https://en.wikipedia.org/wiki/Glutamic_acid) or [glutamine](https://en.wikipedia.org/wiki/Glutamine). So every letters in English Alphabet are covered except Letter J, are there any considerations?

**Comment by dariotommasini** [comment]
Hello! Is there a recommended solution for this? Should we substitute an X for every J in a protein record before calling extract.py?

**Comment by zhoubay** [comment]
> Hello! Is there a recommended solution for this? Should we substitute an X for every J in a protein record before calling extract.py?

Yeah, I think it is the best solution
