### ISSUE TITLE
Missing model.eval() in main README

### ISSUE THREAD

**Issue by samgelman** [facebookresearch/esm#169]
First, thanks for making these models available and easily accessible! 
The "quick start" example in the main README is missing a call to model.eval().

**Comment by samgelman** [comment]
I just searched through the closed issues, and I see that was intentional. Might still be good to clarify on the README. Otherwise, feel free to close this issue! Thanks!

**Comment by tomsercu** [comment]
Thanks for flagging, yes it has lead to confusion and worth including even in the minimal quickstart example.
