### ISSUE TITLE
calculate the log likelihood of 2 chains vs a 3rd?

### ISSUE THREAD

**Issue by avilella** [facebookresearch/esm#195]
Is it possible to use the log likelihood script to calculate the joined log likelihood of 2 input fasta chains against the 3rd chain in a pdb file?

E.g. If the pdb has chains H, L, and A, could we use the script to feed in the fasta sequences of a query H + a query L of the same length as H and L, then get the likelihood against chain A in the pdb?

If the answer is "not easily", could we somehow re-write the pdb to pretend that H+L are the same chain, maybe by renaming HL and adding a link in the pdb file between the two, then run the log likelihood on "HL" vs the edited pdb?

Thanks

**Comment by tomsercu** [comment]
That seems like a totally reasonable thing to do. It'll just be a matter of setting it up right.
See the paper [Hsu et al. 2022](https://www.biorxiv.org/content/10.1101/2022.04.10.487779v1) subsection on protein complexes, for one way to set this up: by concatenating together with 10 mask tokens between chains.
Other creative ways may be possible, feel free to share and discuss in the Discussions tab of this repo!
