### ISSUE TITLE
About huggingface support for esm

### ISSUE THREAD

**Issue by chang-github-00** [facebookresearch/esm#198]
I see a new model card on huggingface  https://huggingface.co/facebook. However, I can't successfully import this model because the released transformers don't support esm models.
```
from transformers import ESMForMaskedLM, ESMTokenizer
tokenizer = ESMTokenizer.from_pretrained("facebook/esm-1b", do_lower_case=False )
model = ESMForMaskedLM.from_pretrained("facebook/esm-1b")
sequence_Example = "QERLKSIVRILE"
encoded_input = tokenizer(sequence_Example, return_tensors='pt')
output = model(**encoded_input)
```
I wonder when will this version be fully released. Many thanks!

**Comment by chang-github-00** [comment]
This seems to be solved by 
'''
git clone -b add_esm-proper --single-branch https://github.com/liujas000/transformers.git 
pip -q install ./transformers
'''

**Comment by dashapyly** [comment]
yes getting this to work would be nice - thank you

**Comment by jlotthammer** [comment]
+1 a long term solution here would be very great!

**Comment by felixgabler** [comment]
> This seems to be solved by
> 
> ```
> git clone -b add_esm-proper --single-branch https://github.com/liujas000/transformers.git 
> pip -q install ./transformers
> ```

While this generally works, I noticed that the tokenizer uses `1` (= "-") instead of `2` (= "<pad>") for end-of-sequence padding as described here https://github.com/facebookresearch/esm/discussions/126. Do you think this could be an issue?

**Comment by tomsercu** [comment]
Very happy to share that - thanks to the amazing work of @Rocketknight1 and 🤗 team - this is now supported:

> Classification tasks with proteins, just like BERT: https://colab.research.google.com/github/huggingface/notebooks/blob/main/examples/protein_language_modeling.ipynb
> 
> Fold proteins in Colab or your local GPU and export PDB files: https://colab.research.google.com/github/huggingface/notebooks/blob/main/examples/protein_folding.ipynb
