### ISSUE TITLE
Bias of chosing amino acid for inverse folding

### ISSUE THREAD

**Issue by vuhongai** [facebookresearch/esm#199]
Dear authors,

Thank you for sharing your amazing work.
I however would like to report this phenomenon, maybe a bug, maybe not.

When I do the inverse folding with defined backbone, I would like to fix (seed) about 50-100 amino acids at the begining and it results in designed sequence dominated with leucine (L), regardless the tempature (I chose maximum temperature is 1, if temp>1, this bias will be much less). Did you obseve this bias before in your design?

Best regards,
Ai

**Comment by tomsercu** [comment]
Thanks for sharing this failure mode.
This would of course depend on the specifics of the backbone you present to the model, as well as the fixed part of the sequence. If either of those were out of distribution or malformed (ie not corresponding to a real structure/sequence combination), I would not expect the model to produce anything reasonable.
