### ISSUE TITLE
Using the same input for the inverse_folding model  will produce different outputs 

### ISSUE THREAD

**Issue by lupengk** [facebookresearch/esm#202]
**Problem description**
When I run the script "examples/inverse_folding/score_log_likelihoods.py" repeatedly, it always produces different output, and the output is very different

**Reproduction steps**
run the script "examples/inverse_folding/score_log_likelihoods.py" repeatedly
```python
python examples/inverse_folding/score_log_likelihoods.py examples/inverse_folding/data/5YH2.pdb \
    examples/inverse_folding/data/5YH2_mutated_seqs.fasta --chain C \
    --outpath examples/inverse_folding/output/5YH2_mutated_seqs_scores.csv
```
The output varies greatly

**Comment by tomsercu** [comment]
Setting the model in `eval` mode should fix this issue. It's being addressed in #206 
Please feel free to re-open if that didn't properly address the problem! Thanks
