### ISSUE TITLE
train data problem

### ISSUE THREAD

**Issue by Wangchentong** [facebookresearch/esm#204]
Hi, thanks all of you for your great work, i want to know the data that af2 predict of uniref 50 to train esm-IF model will be available to download or it is private? since it is very useful to do some other task and whould be nice if you guys can share.

**Comment by tomsercu** [comment]
Thank you!
We are still considering the feasibility of making the large predicted structure dataset available.
See https://github.com/facebookresearch/esm/discussions/194
