### ISSUE TITLE
Request of raw prediction scores for zero-shot variant prediction

### ISSUE THREAD

**Issue by Stephen2526** [facebookresearch/esm#210]
Hello ESM team,

I really appreciate your line of great works on protein language modeling.

I am wondering is it possible that you can share the raw prediction scores of each mutation for these 41 DMS sets. Specifically, I mean the dataset below:

`raw_df` (available upon request): every row contains one mutation for a specific protein (multi-index: ["protein_name", "mutant"]) and columns are different prediction methods.

Thanks a lot

**Comment by tomsercu** [comment]
Sure, it was just to big for polluting the github repo. Now available at https://dl.fbaipublicfiles.com/fair-esm/examples/variant-prediction/data/raw_df.csv
