### ISSUE TITLE
Embeddings for protein structures

### ISSUE THREAD

**Issue by sky-2002** [facebookresearch/esm#225]
Hello @joshim5, @tomsercu , @sbonner0 😇 ! I am new to this repository. I was looking for something that can be used to get embeddings for structures of proteins and was suggested to use this repository. Would you please let me know if the models mentioned and available in the repository can be used to get embeddings for protein structures ??

**Comment by tomsercu** [comment]
Yes you can look at the README page for instructions. Most models are sequence-first, but you could use ESM-IF1 for a kind of structure embeddings.
Feel free to use this place for discussions if you get stuck: https://github.com/facebookresearch/esm/discussions
