### ISSUE TITLE
Unsupervised ﬁne-tuning ESM-1v script

### ISSUE THREAD

**Issue by NingNing-C** [facebookresearch/esm#229]
Hi,
Great work! I'm wondering if you could provide the unsupervised fine-tuning script described in zero-shot paper? Or maybe suggest how to do the unsupervised fine-tuning for a specific protein family? Many thanks!

**Comment by tomsercu** [comment]
Thank you! You'd just need a standard pytorch training loop and the MSA of a protein family, as described in paper Section 4.4 and Appendix B. Here's a discussion on finetuning with some further pointers: #33
