### ISSUE TITLE
read_msa in examples/variant-prediction does not remove insertions

### ISSUE THREAD

**Issue by Jacoberts** [facebookresearch/esm#230]
Hi all! Very excited to use MSA Transformer. Our calls to predict.py were failing due to MSA length mismatches [1]. Comparing [read_msa in predict.py]( https://github.com/facebookresearch/esm/blob/e5e7b06b9a093706607c229ab1c5c9821806814d/examples/variant-prediction/predict.py#L20) to [read_msa in contact_prediction.ipynb](https://github.com/facebookresearch/esm/blob/main/examples/contact_prediction.ipynb?short_path=527384c#L368) makes me think that it's missing the `remove_insertions` functionality.

I'm gonna try adding that and seeing if it works!

[1]
```
Transferred model to GPU
Traceback (most recent call last):
  File "/code/esm/examples/variant-prediction/predict.py", line 239, in <module>
    main(args)
  File "/code/esm/examples/variant-prediction/predict.py", line 165, in main
    batch_labels, batch_strs, batch_tokens = batch_converter(data)
  File "/opt/conda/lib/python3.7/site-packages/esm/data.py", line 325, in __call__
    "Received unaligned sequences for input to MSA, all sequence "
RuntimeError: Received unaligned sequences for input to MSA, all sequence lengths must be equal.
```

**Comment by tomsercu** [comment]
Thanks so much for identifying and fixing this issue!
