### ISSUE TITLE
When using ESM-MSA-1b, is the MSA generated in real-time from the input sequence or is it fixed?

### ISSUE THREAD

**Issue by walt676** [facebookresearch/esm#235]
Thank you for sharing such outstanding work.
I looked up the MSA Transformer related example code under the `example` folder, but it looks like msa is read from a file. For the new input sequence, do I need to generate a new msa file?
If so, in which part of the repo can this part of the code be found (code for generating msa file according to input sequence)?

**Comment by tomsercu** [comment]
Yes the MSA needs to be provided, this can be done using the standard tools eg HHblits, JackHMMER, MMSeqs etc.
