### ISSUE TITLE
Decoding an embedding back to a sequence

### ISSUE THREAD

**Issue by martin-steinegger** [facebookresearch/esm#24]
Thank you for this resource! I am currently trying to predict a protein sequence from an embedding. 
Is it possible to load the decoder of the ESM model? Is there an example snippet I could use?

**Comment by joshim5** [comment]
Hi Martin! ESM is an encoder-only model (like BERT) - there is no decoder.

Are you looking for the language modeling head, i.e. the final layer of the network? If so, check out this reference code for [ESM-1](https://github.com/facebookresearch/esm/blob/master/esm/model.py#L159) and [ESM-1b](https://github.com/facebookresearch/esm/blob/master/esm/model.py#L157). 

Feel free to reopen the issue if you have any more questions!

**Comment by martin-steinegger** [comment]
@joshim5 Hi Joshua! That was a blazing fast answer. Thanks.

**Comment by Leo-T-Zang** [comment]
Hi @martin-steinegger ,
Did you find a way to decode the embeddings? I am also looking for a way to do it.
Thanks.
