### ISSUE TITLE
MSA dataset

### ISSUE THREAD

**Issue by EBGU** [facebookresearch/esm#244]
Hi! 
I am currently following your great work MSA Transformer, and I would like to reproduce it myself. I wonder if it is possible to download the 4.3T msa dataset you used in this paper? Thank you so much!
Best,
Yinjun

**Comment by tomsercu** [comment]
It is currently not publicly available. We are looking into releasing it.

**Comment by pzhang84** [comment]
Is it possible to use the trained model for inference on single protein sequences?
