### ISSUE TITLE
training code for unsupervised contact prediction

### ISSUE THREAD

**Issue by zhenyuhe00** [facebookresearch/esm#249]
Hi guys,

Congrats on the excellent work and great results.
May I ask do you plan to release the code for training unsupervised contact prediction?

Thanks in advance.

**Comment by zhenyuhe00** [comment]
Find same issues #229 , so close this one

**Comment by zhenyuhe00** [comment]
Find same issues #229 , so close this one

**Comment by rmrao** [comment]
This is trained using scikit-learn with the following parameters

```python
X = [N x (num_layers * num_attn_heads)] - 2D feature array, each entry is the attentions for one contact (i, j) for one protein
y = [N x 1] - 2D boolean array, whether or not each entry corresponds to a contact
clf = sklearn.linear_model.LogisticRegression(
    penalty="l1",
    C=0.15,
    solver="liblinear",
)
clf.fit(X, y)
```

**Comment by zhenyuhe00** [comment]
Thanks a lot!

**Comment by zhenyuhe00** [comment]
I wonder what is the parameter for "max_iter"

**Comment by zhenyuhe00** [comment]
default iteration is probably enough
