### ISSUE TITLE
Where to download the CAMEO hard targets

### ISSUE THREAD

**Issue by zhenyuhe00** [facebookresearch/esm#250]
Hi guys,

Congrats on the excellent work and great results.
May I ask where to download the CAMEO hard targets?

Thanks in advance.

**Comment by tomsercu** [comment]
Hi @zhenyuhe00, here is the cameo website, you can filter by Easy/medium/Hard and by datestamp: https://www.cameo3d.org/modeling/targets/1-year/difficulty/hard/?to_date=2022-08-13
