### ISSUE TITLE
ModuleNotFoundError - "model" directory is missed in setup.py

### ISSUE THREAD

**Issue by ptynecki** [facebookresearch/esm#253]
**Bug description**
"[model](https://github.com/facebookresearch/esm/tree/main/esm/model)" directory is missed in "[packages](https://github.com/facebookresearch/esm/blob/main/setup.py#L25)" argument in setup.py script. That issue raised `ModuleNotFoundError: No module named 'esm.model'` exception.

**Reproduction steps**
Try to install `esm` package from PyPI or from the GitHub repository.

**Expected behavior**
I was expected successful installation.

**Logs**
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Input In [1], in <cell line: 2>()
      1 import torch
----> 2 import esm

File ~/protein_embeddings/env/lib/python3.8/site-packages/esm/__init__.py:9, in <module>
      6 from .version import version as __version__  # noqa
      8 from .data import Alphabet, BatchConverter, FastaBatchedDataset  # noqa
----> 9 from .model.esm1 import ProteinBertModel  # noqa
     10 from .model.esm2 import ESM2  # noqa
     11 from .model.msa_transformer import MSATransformer  #noqa

ModuleNotFoundError: No module named 'esm.model'
```

**Comment by brycejoh16** [comment]
having the same issue right now looking for a solution.

**Comment by ptynecki** [comment]
@brycejoh16 

PR is waiting:
https://github.com/facebookresearch/esm/pull/254

**Comment by brycejoh16** [comment]
@ptynecki thank you!

**Comment by ptynecki** [comment]
@tomsercu PR #254 is resolving the issue problem but there is another during the installation.

The `fairscale` package is required (not added to setup.py as well).

**Comment by nikitos9000** [comment]
Hi @ptynecki @brycejoh16 thanks for spotting that! It's fixed now in https://github.com/facebookresearch/esm/pull/254, the fairscale dependency will be fixed soon.

**Comment by tomsercu** [comment]
Thanks yes much about our build/release process could be improved. 
#256 addressed the fairscale dependency.
@ptynecki let us know if your issues are resolved now. Thanks all for your input!
