### ISSUE TITLE
unable to import esm

### ISSUE THREAD

**Issue by pengzhangzhi** [facebookresearch/esm#257]
I install by ` pip install fair-esm`.
Then try the example code:
```python

import torch
import esm

# Load ESM-2 model
model, alphabet = esm.pretrained.esm2_t48_15B_UR50D()
batch_converter = alphabet.get_batch_converter()
model.eval()  # disables dropout for deterministic results

```

The following error is raised:
```bash
ModuleNotFoundError                       Traceback (most recent call last)
Untitled-1.ipynb Cell 1 in <cell line: 2>()
      [1](vscode-notebook-cell:Untitled-1.ipynb?jupyter-notebook#W0sdW50aXRsZWQ%3D?line=0) import torch
----> [2](vscode-notebook-cell:Untitled-1.ipynb?jupyter-notebook#W0sdW50aXRsZWQ%3D?line=1) import esm
      [4](vscode-notebook-cell:Untitled-1.ipynb?jupyter-notebook#W0sdW50aXRsZWQ%3D?line=3) # Load ESM-2 model
      [5](vscode-notebook-cell:Untitled-1.ipynb?jupyter-notebook#W0sdW50aXRsZWQ%3D?line=4) model, alphabet = esm.pretrained.esm2_t48_15B_UR50D()

File ~/anaconda3/envs/torch/lib/python3.8/site-packages/esm/__init__.py:9, in <module>
      6 from .version import version as __version__  # noqa
      8 from .data import Alphabet, BatchConverter, FastaBatchedDataset  # noqa
----> 9 from .model.esm1 import ProteinBertModel  # noqa
     10 from .model.esm2 import ESM2  # noqa
     11 from .model.msa_transformer import MSATransformer  #noqa

ModuleNotFoundError: No module named 'esm.model.esm1'; 'esm.model' is not a package

```

**Comment by ptynecki** [comment]
@pengzhangzhi Reinstall the package from **main** branch.

**Comment by tomsercu** [comment]
Yes it sounds like a version conflict. Can you `pip uninstall` and then `pip install` again and make sure the version is 1.0.2 which just appeared on pip today?

**Comment by donovanr** [comment]
I also have this problem, installing from main and also from pypi with `fair-esm==1.0.2` into a fresh conda env with `python=3.9` on linux.

**Comment by dikshyantg** [comment]
I also have a similar problem when I try to run the extract.py script

File "/home/dikshyant/anaconda3/lib/python3.7/site-packages/esm/__init__.py", line 9, in <module>
    from .model.esm1 import ProteinBertModel  # noqa
ModuleNotFoundError: No module named 'esm.model.esm1'; 'esm.model' is not a package

**Comment by pooriyapfn** [comment]
I had this issue too, but I could run it with a trick.
first of all uninstall your package and use this command:

```
pip install git+https://github.com/facebookresearch/esm.git
```

after that if you are using Jupyter (like colab), first run this block of code, to download the model completely:


```
import torch
import esm

model, alphabet = esm.pretrained.esm2_t36_3B_UR50D()
```

after several minutes you can run rest of your code.

![Screen Shot 1401-06-02 at 3 02 41 PM](https://user-images.githubusercontent.com/7430324/186413481-7887d2aa-62b3-41a3-9bf4-0b08a21dd938.png)

**Comment by tomsercu** [comment]
Hi folks thanks for flagging this issue. The build was broken due to an old file (`model.py`) accidentally being included in the pip wheel. Note that there was no issue on the github main branch, so as @pooriyapfn  points out `pip install git+https://github.com/facebookresearch/esm.git` still worked.

The wheel is fixed now, so please go ahead and pip uninstall, then `pip install fair-esm` or `pip install fair-esm==1.0.2`.

Sorry for the inconvenience.

**Comment by pengzhangzhi** [comment]
Problem solved! Happy to see that!
