### ISSUE TITLE
Contact-map

### ISSUE THREAD

**Issue by nasserhashemi** [facebookresearch/esm#26]
Hi
Thanks again for your great repositories;
I have a question; how did you calculate contact map in your pre-retrained model? Have you used any supervising datasets or just use the embedded representation of amino acids and pairwise scoring?
Thanks
Nasser

**Comment by tomsercu** [comment]
Hi Nasser,
Thanks for your question -- It's a logistic regression mapping the attention heads to the contact map, logistic regression weights trained on only 20 proteins. As described in [our recent paper to appear at ICLR](https://openreview.net/pdf?id=fylclEqgvgd).

**Comment by nasserhashemi** [comment]
Thanks so much 
Great
