### ISSUE TITLE
details of  outerdifference

### ISSUE THREAD

**Issue by zhenyuhe00** [facebookresearch/esm#263]
Hi,
I read your ESM-2 paper and I'm curious about the details of outerdifference.
the outer product  is calculated as: (c, 1) dot (1, c) → (c, c)
So I wonder if outer difference is calculated as: (c, 1) - (1, c) → (c, c)  by pytorch broadcast

Thanks in advance!

**Comment by tomsercu** [comment]
yes that sounds right.
It is evolved from the "outer concatenation" described in Wang et al 2017 Accurate De Novo Prediction of Protein Contact Map by Ultra-Deep Learning Model

**Comment by zhenyuhe00** [comment]
many thanks!
