### ISSUE TITLE
ESM folding block

### ISSUE THREAD

**Issue by gdharuman11** [facebookresearch/esm#269]
Hi,

I was wondering if the folding trunk and structure modules have been released? I am unable to find them. We are interested in scaling esmfold to genome data. Thanks in advance!

**Comment by tomsercu** [comment]
ESMFold release is coming soon :)

**Comment by nibtehaz** [comment]
Hi, thank you for making the ESM2 models public. Would you kindly share when ESM-FOLD will be released?
