### ISSUE TITLE
use of bos and eos token when training

### ISSUE THREAD

**Issue by zhenyuhe00** [facebookresearch/esm#299]
Hi, 
Congrats on your great work.
I wonder did you use prepend bos and eos for every cropped sequence, or did you prepend bos and eos only for the complete protein sequence?

Thanks in advance!

**Comment by tomsercu** [comment]
On all sequences, even cropped ones.

**Comment by felbecker** [comment]
@tomsercu In the ESM2 paper it says the opposite:

> We used BOS and EOS tokens to signal the beginning and end of a real 
> protein, to allow the model to separate a full-sized protein from a cropped one

**Comment by y-hwang** [comment]
@tomsercu I have the same question as @felbecker. Were partial/truncated proteins prepended and appended with bos/eos during training? thank you!
