### ISSUE TITLE
Using ESM2 for structure prediction

### ISSUE THREAD

**Issue by YFeriel** [facebookresearch/esm#311]
I am studying the 3D structure of alternative proteins. I have a dataset of more than 500000 proteins among which 300000 have a msa lower than 30. So I use your ESM2 model to predict their structures. However, I generate only the contact matrices.

Could you guide me on how to generate the 3D structures in pdb or other format? Do you couple ESM2 to AlphFold to generate the structures?

**Comment by tomsercu** [comment]
ESMFold will be released relatively soon.
