### ISSUE TITLE
Wrong colab link for inverse folding multichain notebook

### ISSUE THREAD

**Issue by chloechsu** [facebookresearch/esm#312]
The "Open in Colab" link points to https://colab.research.google.com/github/facebookresearch/esm/blob/main/examples/inverse_folding/notebook.ipynb instead of https://colab.research.google.com/github/facebookresearch/esm/blob/main/examples/inverse_folding/notebook_multichain.ipynb

**Comment by tomsercu** [comment]
Hi @chloechsu just to make sure - you want the button on the frontpage README to point to the multichain version, right?  Other links inside examples/inverse_folding/README looked correct to me.
If yes we can merge #379
