### ISSUE TITLE
why use \ as the break line

### ISSUE THREAD

**Issue by ShallowDream0218** [facebookresearch/esm#320]
NOTE: if this is not a bug report, please use the [GitHub Discussions](https://github.com/facebookresearch/esm/discussions) for support questions (How do I do X?), feature requests, ideas, showcasing new applications, etc.

**Bug description**
Please enter a clear and concise description of what the bug is.

**Reproduction steps**
Enter steps to reproduce the behavior.

**Expected behavior**
Give a clear and concise description of what you expected to happen.

**Logs**
Please paste the command line output:

```
Output goes here
```

**Additional context**
Add any other context about the problem here. (like proxy settings, network setup, overall goals, etc.)

**Comment by ShallowDream0218** [comment]
after the cmd, i almost thought some wrong with torch.save(),but every run successed,i waste my 4 days to find where is the problem. you know? 4days wasted to solve this fucking problem,and it's just a fucking fool wrong misunderstanding of the signal "\" .you can just use a normal space as a break, i thought "\" is a part of parameters,how could you do this to me? i almost lost my confidence to continue my graduate life,and i almost lose my life bcz of it TAT

**Comment by tomsercu** [comment]
Hi @ShallowDream0218 , sorry that you're not feeling great.  Please take care
