### ISSUE TITLE
Is it possible to train the ESMFold model based on the openfold ？

### ISSUE THREAD

**Issue by pengshuang** [facebookresearch/esm#327]
Thanks for releasing the ESMFold code for structure prediction！

However, I wonder what is the best way to train the ESMFold from the scratch. To be specific, I want to finetune the ESMFold model based on the ESM2 weights. I notice that the ESMFold [code](https://github.com/facebookresearch/esm/blob/main/esm/esmfold/v1/esmfold.py) partly relies on [openfold](https://github.com/aqlaboratory/openfold), and I want to know whether is it possible to train the ESMFold model based on the openfold.

Hope for your suggestions. Thanks in advance!

**Comment by ebetica** [comment]
Hey! Our training code is not released. It's already trained on esm2-3B.
