### ISSUE TITLE
No module named 'openfold'

### ISSUE THREAD

**Issue by yesols** [facebookresearch/esm#336]
Hello! When I tried to run `scripts/esmfold_inference.py`, I got this error: 
```
  File "/Users/yesol/opt/anaconda3/envs/ml/lib/python3.9/site-packages/esm/esmfold/v1/esmfold.py", line 11, in <module>
    from openfold.data.data_transforms import make_atom14_masks
ModuleNotFoundError: No module named 'openfold'
```
I found github page for OpenFold. Do I need to install this first? If so, did I miss this somehow in the installation instruction? Or can I just copy their `data_transforms.py` script if this is the only part used in ESM? 

Thank you very much.

**Comment by JasperGeissler** [comment]
Hello,

May I ask how you found the solution to your problem? I'm struggling with a very similar problem.
Thanks in advance!

**Comment by yesols** [comment]
Hi @JasperGeissler ,
It was a hardware issue in my case. I simply realized that my computer was not CUDA-compatible which was mentioned in the installation instruction but I overlooked it. I ended up using the colab environment.
