### ISSUE TITLE
How to search sequences in bulk？

### ISSUE THREAD

**Issue by 1185307269** [facebookresearch/esm#341]
Dear all:
  I have a question: How can I do a bulk search sequences in the web version?
![image](https://user-images.githubusercontent.com/103171497/200107980-555ac02e-695b-4302-a040-b5f8971013ca.png)
Or can I download it through an API?

**Comment by tomsercu** [comment]
Unfortunately we don't support bulk sequence search, you should use `mmseqs` directly. We'll upload a fasta file and pre-computed mmseqs db.

**Comment by 1185307269** [comment]
Thank you very much for your reply! 
Where can I download the fasta file and the pre-computed mmseqs db?

**Comment by ebetica** [comment]
I uploaded the high quality fasta here:

```
s3://dl.fbaipublicfiles.com/esmatlas/v0/highquality_clust30/highquality_clust30.fasta
```

And mgnify90 here:

```
s3://dl.fbaipublicfiles.com/esmatlas/v0/full/mgnify90.fasta
```

**Comment by 1185307269** [comment]
Thank you very much for your reply！！！！！But I have one more stupid question to ask: what is the difference between these two databases? If I have some sequences to search, which database should I take for searching?

**Comment by ebetica** [comment]
The high quality is a subset of mgnify90 which is redundancy reduced and well predicted by ESMFold (pTM & pLDDT > 0.7)

**Comment by tomsercu** [comment]
We now provide https://dl.fbaipublicfiles.com/esmatlas/v0/full/atlas.fasta with 617051007 records precisely matching stats.parquet.

See #366 for more context
