### ISSUE TITLE
No module named 'openfold'

### ISSUE THREAD

**Issue by sweetcodeer** [facebookresearch/esm#354]
I used the following command in kaggle to install esm ：

!pip install fair-esm[esmfold]
!pip install 'dllogger @ git+https://github.com/NVIDIA/dllogger.git'
!pip install 'openfold @ git+https://github.com/aqlaboratory/openfold.git@4b41059694619831a7db195b7e0988fc4ff3a307'

However, the following problems occur, I cannot install openfold, may I ask how to deal with this?

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-b_m2a11p/openfold_e5eab7d3734d4847886515a36ffc97f8/setup.py", line 56, in <module>
          _, bare_metal_major, _ = get_cuda_bare_metal_version(CUDA_HOME)
        File "/tmp/pip-install-b_m2a11p/openfold_e5eab7d3734d4847886515a36ffc97f8/setup.py", line 40, in get_cuda_bare_metal_version
          raw_output = subprocess.check_output([cuda_dir + "/bin/nvcc", "-V"], universal_newlines=True)
      TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

this: 

----> 5 from esm.esmfold.v1.esmfold import ESMFold
----->ModuleNotFoundError: No module named 'openfold'

**Comment by sweetcodeer** [comment]
I would appreciate it if it could be resolved.

**Comment by tomsercu** [comment]
Openfold installation fails due to `nvcc` which is the cuda compiler. Resolving this is specific to many things like OS and cuda version etc. I'd recommend to use the huggingface port or colabfold, which will sidestep this problem entirely. Pointers in frontpage README.
