### ISSUE TITLE
Mapping between MGYP ID and Uniprot ID

### ISSUE THREAD

**Issue by blackjack6666** [facebookresearch/esm#357]
Hello,

First of all I want to say thanks for the fantastic work! And I just wonder if you have provided any mapping between the MGYP ID and Uniprot ID? I wanted to download some structures based on Uniprot ID from ESM atlas, and it seems I could only search for structures based on MGYP ID?

Thank you!

**Comment by ebetica** [comment]
There's no such mapping afaik, Mgnify and Uniprot are two completely different sequence databases.

**Comment by tomsercu** [comment]
Just note that the best you could do probably is sequence search from either one of the dtabases as source and either one is target if you need an approximate nearest neighbor. you could look at `mmseqs search --max-accept 3`
