### ISSUE TITLE
no matches found: fair-esm[esmfold]

### ISSUE THREAD

**Issue by tdiethe** [facebookresearch/esm#365]
When I run `pip install fair-esm[esmfold]` I get `no matches found: fair-esm[esmfold]`

❯ uname -a
Linux ip-10-0-139-177 5.4.0-1088-aws #96~18.04.1-Ubuntu SMP Mon Oct 17 02:57:48 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
❯ python --version
Python 3.9.13

**Comment by jlotthammer** [comment]
If you throw it in quotes `pip install "fair-esm[esmfold]"` I think it should work - it does for me. At least the esmfold aspect, I'm still having issues getting the openfold / openfold dependencies installed.

**Comment by tdiethe** [comment]
Aha yes that worked thanks!

**Comment by tdiethe** [comment]
I guess you're getting the following error:

`ModuleNotFoundError: No module named 'scripts.utils'`
