### ISSUE TITLE
Provide predicted aligned error (PAE) json file download on atlas web pages

### ISSUE THREAD

**Issue by tomgoddard** [facebookresearch/esm#369]
The ESM Metagenomic Atlas web pages allow downloading the PDB structure and sequence but don't offer any button to download the predicted aligned error (PAE) although that error is plotted on the web page.  Here is an example atlas page

https://esmatlas.com/explore/detail/MGYP000086941770

It would be useful to have button on entry pages to download the PAE json file.  These error estimates are often critical for a biologist to know if the domains of the protein are packed correctly.  The json file can be viewed along with the PDB structure and sequence in the ChimeraX molecular viewer and that capability is widely used for AlphaFold.

**Comment by tomgoddard** [comment]
The PAE data is available via a REST API as described here

    https://esmatlas.com/about#api

such as

   curl "https://api.esmatlas.com/fetchPredictedStructure/MGYP002537940442"

but few biologists will be able to find that.

**Comment by tomsercu** [comment]
Small corection the API endpoint is
`https://api.esmatlas.com/fetchConfidencePrediction/MGYP002537940442`

And the PAE is rendered on the detail page but for short proteins only.

**Comment by tomsercu** [comment]
Oh sorry I see this is a feature request. I'll add this request to our feature tracker and prioritize accordingly. Thank you!
