### ISSUE TITLE
Provide predicted aligned error (PAE) from the ESM Metagenomic Atlas prediction API

### ISSUE THREAD

**Issue by tomgoddard** [facebookresearch/esm#370]
Currently predictions run with the ESM Metagenomic Atlas API, for example

`curl -X POST --data "GENGEIPLEIRATTGAEVDTRAVTAVEMTEGTLGIFRLPEEDYTALENFRYNRVAGENWKPASTVIYVGGTYARLCAYAPYNSVEFKNSSLKTEAGLTMQTYAAEKDMRFAVSGGDEVWKKTPTANFELKRAYARLVLSVVRDATYPNTCKITKAKIEAFTGNIITANTVDISTGTEGSGTQTPQYIHTVTTGLKDGFAIGLPQQTFSGGVVLTLTVDGMEYSVTIPANKLSTFVRGTKYIVSLAVKGGKLTLMSDKILIDKDWAEVQTGTGGSGDDYDTSFN" https://api.esmatlas.com/foldSequence/v1/pdb/
`

described here

    https://esmatlas.com/about#api

does not give any way to get the predicted aligned error (PAE).  The PAE data is a key aspect of the prediction indicating if the protein domains are packed correctly.  It would be very useful to provide both the PDB predicted structure and JSON PAE file.  One way to achieve this would be to create a new REST API that returns a zip file containing the PDB and JSON files.

**Comment by tomgoddard** [comment]
The PAE data can be viewed and interactively analyzed together with the protein structure in the ChimeraX visualization program that I develop.  I've added an ESMFold prediction capability to ChimeraX using the Meta server and would like it to be able to get the PAE data.

     https://www.rbvi.ucsf.edu/chimerax/data/esmfold-nov2022/esmfold.html

**Comment by tomsercu** [comment]
Hi Tom, thanks for your work on ChimeraX, we were impressed by the beautiful visualizations!
I'll add this feature request to our internal tracker and prioritize accordingly.

**Comment by tomgoddard** [comment]
Thanks!
