### ISSUE TITLE
ESM Metagenomic Atlas website not working

### ISSUE THREAD

**Issue by KexinNiu** [facebookresearch/esm#373]
Hello ESM team, 

The website [ESM Metagenomic Atlas](https://esmatlas.com/) is not working. 

Thank you.

**Comment by nikitos9000** [comment]
Hi @KexinNiu I can see the website is ok now. Could you confirm this on your side please?

**Comment by KexinNiu** [comment]
> Hi @KexinNiu I can see the website is ok now. Could you confirm this on your side please?

Yes, the problem is from my side and it is fixed now. Thank you so much for your help.
