### ISSUE TITLE
stats.parquet file for ESM Metagenomic Atlas has duplicate entries

### ISSUE THREAD

**Issue by tomgoddard** [facebookresearch/esm#376]
Here is an example of the duplicate entries in the stats.parquet file with the same MGnify id.  The are the same except for differing ptm values.  It seems there should not be duplicates since I believe each MGnify id has only one structure prediction in the atlas.  

```
                         id    ptm  plddt  num_conf  len                                                                                 
521608462  MGYP000000011531  0.679  0.842        28   33                                                                                 
577478634  MGYP000000011531  0.490  0.842        28   33                                                                                 
577528622  MGYP000000011531  0.622  0.842        28   33  
```
This is the stats.parquet file I used is

    https://dl.fbaipublicfiles.com/esmatlas/v0/stats.parquet

The link to the stats.parquet file 

    https://dl.fbaipublicfiles.com/esmatlas/v0.0/stats.parquet

on the Atlas API web page

    https://esmatlas.com/about#api

is broken, gives an Access Denied error.

**Comment by tomsercu** [comment]
Thanks for flagging that broken link, it's fixed now.
cc @ebetica for fixing the stats.parquet file, this one is based on an old early version of the database before filling in missing entries and dedups

**Comment by tomgoddard** [comment]
Thanks!  My main interest in stats.parquet was to get the list of MGnify identifiers for the database so that I could create a file of all the sequences for searching.  You provided the sequence file in #366 which has solved that problem.  But I may still uses stats.parquet to do filtering my model scores.

**Comment by tomsercu** [comment]
Ah yes happy we have the right data in place now! :)
