### ISSUE TITLE
ESM-MSA-1 from pytorch hub

### ISSUE THREAD

**Issue by ryan-224** [facebookresearch/esm#40]
Hi there,

Thanks for making this work public.

I was trying to load the MSA-1 model from pytorch hub, but it seems that it is not on the list yet.

Could you please add the msa-1 model to hubconf.py?

Thanks a lot again.

**Comment by tomsercu** [comment]
Thanks for flagging this oversight! This is fixed now; try
`model, alphabet = torch.hub.load("facebookresearch/esm", "esm_msa1_t12_100M_UR50S")`
You may need to clear cache in `~/.cache/torch/hub/facebookresearch_esm_master`
