### ISSUE TITLE
Question about confidence determination

### ISSUE THREAD

**Issue by alpha-omega-labs** [facebookresearch/esm#426]
Hello,
Thank you very much for ESM Fold! 
During prediction here is a sample output:
<pre>
Predicted structure for X with length 337, pLDDT 84.5, pTM 0.687 in 9.0s. 1 / 2 completed
</pre>

Question:
How exactly pTM counted in case of ESM Fold prediction? With what structures/fragments alignments are made or other way? 
Thank you!

**Comment by tomsercu** [comment]
pTM captures the model's confidence, it stands for "predicted TM-score". It is well-calibrated with actual TM-score to target  structure which is presented during supervised training, but is a metric that does not need a target itself.

**Comment by alpha-omega-labs** [comment]
Thank you for a fast response. 
Is there a way to measure (with ESM Fold current presented models) pTM for 3rd party .pdb? Roughly compare other party predicted structure with the same sequence predicted by ESM Fold.

**Comment by tomsercu** [comment]
if you have an existing (sequence, structure) pair from your .pdb file, you can give the sequence to ESMFold and it will give you a structure prediction and pTM score. With the predicted structure, you can use TMalign to compute TM-score to the reference structure from the original pdb file.
