### ISSUE TITLE
MSA file

### ISSUE THREAD

**Issue by ryan-224** [facebookresearch/esm#43]
Hi again.

Thank you for adding the MSA-1 model.

I am experimenting if we can get a better representation of proteins for some down-stream tasks with the MSA model.

Do you have any suggestions on how to prepare a proper MSA file (a3m) of a specific protein that fits the model? Like what tools you used, the procedures...

Thanks.

**Comment by tomsercu** [comment]
Hi Ryan, I'd suggest you join the discussion in #42, let me provide some pointers there.
