### ISSUE TITLE
Supervised contact prediction network

### ISSUE THREAD

**Issue by mhj112358** [facebookresearch/esm#44]
Hi guys, 

Congrats for the excellent work and great results. Great to see sequence embedding works indeed. 

May I ask in your MSA Transformer supervised contact prediction network, did you use the outer concat of the query sequence embedding (or with symmetries row self-attention maps) as the only input so that it demonstrates the superior information content of sequence embedding replacing traditional MSA-related features or did you still include all the RaptorX features as input to the resnet as stated in Rives et al 2020? If latter, did you conduct an ablation study like that in Rives et al 2020, to see how much does the sequence embedding contribute to the improved contact precision? 

Thanks in advance.

**Comment by tomsercu** [comment]
Thanks for your interest! In the MSA Transformer supervised results, we have not tried feature combination. Since we're significantly outperforming an identical resnet on potts model features, we expect not much gain anymore from feature combination.
