### ISSUE TITLE
Upload 0.3.0 on pypi?

### ISSUE THREAD

**Issue by hadim** [facebookresearch/esm#45]
See title.

That would be useful for the conda-forge package

**Comment by hadim** [comment]
See https://github.com/conda-forge/bio-embeddings-esm-feedstock

**Comment by tomsercu** [comment]
We will start building and publishing to pypi, pending resolution of https://github.com/pypa/pypi-support/issues/936 
In the meantime, you can install with `pip install git+https://github.com/facebookresearch/esm.git` or use torch hub.
Will update once it's published

**Comment by ashrafgt** [comment]
Thank you @tomsercu 

This is very important for cases where we want to publish a package that uses `esm` as a dependency, and using the `esm @ git+https://github.com/facebookresearch/esm.git` format works for installing locally, but doesn't work when uploading to `pypi` with `twine` (see [issue](https://github.com/pypa/pip/issues/6301))

If possible, we'll push a temp version of the package to `pypi` to progress on our project while we await the official version typ be available.

**Comment by tomsercu** [comment]
Yeah, things don't look too promising on the pypi issue to be resolved anytime soon.
To unblock this, for now we've just published under a different name (could revise when pypi name `esm` gets reassigned). Behold:
```
pip install fair-esm
```
Let us know if that works for you!
cc @konstin

**Comment by tomsercu** [comment]
I'll close this for now but will provide updates if we get the project name released and can switch over  `pip install esm` :)

**Comment by tomsercu** [comment]
And backported the `fair-esm` name to the old releases as well. pypi has now a complete history matching the tags here on github.

**Comment by konstin** [comment]
Thanks! I've migrated bio-embeddings to `fair-esm` and it works flawlessly
