### ISSUE TITLE
Error while installing ESM-2

### ISSUE THREAD

**Issue by anpanche** [facebookresearch/esm#461]
NOTE: if this is not a bug report, please use the [GitHub Discussions](https://github.com/facebookresearch/esm/discussions) for support questions (How do I do X?), feature requests, ideas, showcasing new applications

**Bug description**
I want to use ESM-1v for variants effect predictions.I also read that we can also use ESM-2 for variants predictions. So I was installing ESM-2 using python on azure linux vm .While installing, at the step of openfold installation it gives error. The error says 
error in package openfold not pip install.

I am not able to understand what exactly the error is and how to fix it. Please help me.
Also is GPU necessary for the installation of ESM-2 or ESM1-v? I am not getting precise system requirements for the installation.

**Comment by anpanche** [comment]
I could resolve the problem.

**Comment by JasperGeissler** [comment]
May I ask how you did it? I've encountered a similar problem, and have no idea how to solve it.

Thanks in advance!
