### ISSUE TITLE
How to reproduce MSA Transformer?

### ISSUE THREAD

**Issue by HelloCodingWorld163** [facebookresearch/esm#47]
Hi, I read paper <[MSA Transformer](https://www.biorxiv.org/content/10.1101/2021.02.12.430858v1)>, which achieves an exciting results.

However, I don't know **how to reproduce the result show in paper** ? 

Could somebody help me to do this, thank you ~

**Comment by tomsercu** [comment]
Hi @HelloCodingWorld163 , thanks for your interest!
[Here's an example notebook](https://github.com/facebookresearch/esm/blob/master/examples/contact_prediction.ipynb) using the MSA Transformer weights we released, which can be used to reproduce the unsupervised contact predictions on any MSA.
Let me know if you have any more questions!
