### ISSUE TITLE
hello ,guys ,is there a method to reproduce the pretrain procedure ?

### ISSUE THREAD

**Issue by paulrich1234** [facebookresearch/esm#48]
hello ,guys ,is there a method to reproduce the pretrain procedure ?  

i want to pretrain the model use my own data .

Thank you.

**Comment by tomsercu** [comment]
Hi @paulrich1234 ,
We don't have any near term plans to release pre-training code at this time. 
But for training on your own data, you can use the [fairseq](https://github.com/pytorch/fairseq/) framework directly, which our research codebase sits on top of.
Also see #33 with pointers for finetuning in case that'd be useful to your goal.
Cheers,
