### ISSUE TITLE
ESMFold - Masking specific residues in input FASTA?

### ISSUE THREAD

**Issue by amorehead** [facebookresearch/esm#483]
Hello. Thank you for ESM and ESMFold!

I am trying to find out whether ESMFold supports unknown (i.e., masked) residue types as part of an input FASTA sequence. I have tried replacing specific residues' single-letter characters with `<MASK>`, `<mask>`, `<unk>`, and `X` with little success. When using any of these replacement values in my input FASTA file, the output PDB file ESMFold produces does not contain ATOM entries for these "unknown" (or masked) residues.

Thanks in advance for your input on this!

**Comment by nikitos9000** [comment]
Hi, I think this answers your question partially https://github.com/facebookresearch/esm/issues/477#issuecomment-1438733179 you can use X in the input, but yes, we're not returning coordinates for it at the moment.

**Comment by amorehead** [comment]
Thanks for clarifying!
