### ISSUE TITLE
Broken/outdated URIs in contact_prediction.ipynb

### ISSUE THREAD

**Issue by DanBuchan** [facebookresearch/esm#500]
**Bug description**
When trying to excute the example contact_prediction.ipynb notebook the URIs for the pretrained weights for two of the links are outdated or broken

**Reproduction steps**
Running the Jupyter notebook or running the aria2c command:

```aria2c --dir=/root/.cache/torch/hub/checkpoints --continue --split 8 --max-connection-per-server 8 https://dl.fbaipublicfiles.com/fair-esm/models/esm2_t33_650M_UR50S.pt
```

command fails with HTTP error code 403. These files have either been moved or set to non-readable.

**Expected behavior**

Files would download as described.

It is clear the for the first two links .pt files have just been superseded with newer files and the .ipynb just needs updating to reflect that.

**Comment by nikitos9000** [comment]
Hi, there's probably a typo, please use `https://dl.fbaipublicfiles.com/fair-esm/models/esm2_t33_650M_UR50S.pt` to download this file – I'll update the notebook shortly.
