### ISSUE TITLE
when i use esm_contact_prediction.ipynb ,it has a ' ModuleNotFoundError '

### ISSUE THREAD

**Issue by 313king** [facebookresearch/esm#517]
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-11-ecf9257a1339>](https://localhost:8080/#) in <cell line: 12>()
     10 import matplotlib.pyplot as plt
     11 import matplotlib as mpl
---> 12 from Bio import SeqIO
     13 import biotite.structure as bs
     14 from biotite.structure.io.pdbx import PDBxFile, get_structure

ModuleNotFoundError: No module named 'Bio'

**Comment by tomsercu** [comment]
It should be run in an environment that has BioPython and the other dependencies installed.

**Comment by 313king** [comment]
thank you !  But when i download model weights ,it will show 'download aborted'

**Comment by tomsercu** [comment]
Try it from a different machine? This is definitely a problem specific to your environment. See frontpage README instructions for advice on setting up your environment.
