### ISSUE TITLE
esm_contact_prediction.ipynb -FileNotFoundError

### ISSUE THREAD

**Issue by 313king** [facebookresearch/esm#519]
I have run the conmand '!curl -O https://raw.githubusercontent.com/facebookresearch/esm/main/examples/data/1a3a_1_A.a3m',but is still show "FileNotFoundError: [Errno 2] No such file or directory: 'data/1a3a_1_A.a3m' "

**Comment by tomsercu** [comment]
You can click to confirm this exists:
https://raw.githubusercontent.com/facebookresearch/esm/main/examples/data/1a3a_1_A.a3m

**Comment by 313king** [comment]
Yes,it dose exists ,but when I run ' Read Data'

![colab research google com_drive_1iYo9ImndZfc5Ntea9eXkVp48F3ErXhAi](https://user-images.githubusercontent.com/107452354/229446471-832e2557-ea2f-432d-9bed-333a1730c09a.png)
