### ISSUE TITLE
MSA transformer

### ISSUE THREAD

**Issue by mhj112358** [facebookresearch/esm#54]
Thank you for sharing these excellent results. I'm hoping to clarify on the number of sequences you are sampling in training the MSA transformer (as in the subsample strategy section). 

As I understand (please correct me if I'm wrong), you are using 1024 as sequence length L, so the number of sequences you are sampling is only N/L = 2^14/1024=16? And you are keeping to this number in latter supervised contact prediction as well (you mentioned 256 are used in unsupervised prediction)?

**Comment by tomsercu** [comment]
correct 👍
