### ISSUE TITLE
How I can extract attention map?

### ISSUE THREAD

**Issue by nasserhashemi** [facebookresearch/esm#55]
Hi there; 
I hope you are well; 
I have question, given a sequence as input in esm1b, how I can extract 660 attention map associated with each head in each layer? 
Thanks so much

**Comment by tomsercu** [comment]
Hi Nasser, `model.forward()` has an argument `need_head_weights`, [link](https://github.com/facebookresearch/esm/blob/master/esm/model.py#L114). 
The return dictionary will then contain `result["attentions"]` see L183.
Feel free to re-open if you have any issues!
