### ISSUE TITLE
Embedding proteins in batches with MSA transformer?

### ISSUE THREAD

**Issue by Haxxardoux** [facebookresearch/esm#56]
Passing batches of proteins to the other ESM transformers seems to work fine, but with the MSA transformer, it seems like a specific error is raised - 

![image](https://user-images.githubusercontent.com/59566611/113200197-041f9500-9236-11eb-8891-544020f1db7a.png)

Is there a supported way to encode batches of proteins in a single forward pass?

**Comment by tomsercu** [comment]
Hi Will, seems like you're essentially trying to input a single sequence, while the MSA Transformer expects an MSA (an aligned set of sequences) as input. See [this notebook](https://github.com/facebookresearch/esm/blob/master/examples/contact_prediction.ipynb) for an example.
