### ISSUE TITLE
Local installation help?

### ISSUE THREAD

**Issue by immunoliver** [facebookresearch/esm#590]
Hello,

I'm trying to install ESMfold locally and am struggling. When I paste the following code into the terminal, I get an error message.

pip install "fair-esm[esmfold]"
pip install 'dllogger @ git+https://github.com/NVIDIA/dllogger.git'
pip install 'openfold @ git+https://github.com/aqlaboratory/openfold.git@4b41059694619831a7db195b7e0988fc4ff3a307'

It seems that pip install "fair-esm[esmfold]" works, as does pip install 'dllogger @ git+https://github.com/NVIDIA/dllogger.git', but when I try to install openfold I get the error below:

rekgowr@CS00056653:/mnt/c/Users/rekgowr/Documents/Lab/Structural_Biology$ pip install 'openfold @ git+https://github.com/aqlaboratory/openfold.git@4b41059694619831a7db195b7e0988fc4ff3a307'
Defaulting to user installation because normal site-packages is not writeable
Collecting openfold@ git+https://github.com/aqlaboratory/openfold.git@4b41059694619831a7db195b7e0988fc4ff3a307
  Cloning https://github.com/aqlaboratory/openfold.git (to revision 4b41059694619831a7db195b7e0988fc4ff3a307) to /tmp/pip-install-pxkdmj8r/openfold_3b67dd159eb04815b2101d5537d3d695
  Running command git clone --filter=blob:none --quiet https://github.com/aqlaboratory/openfold.git /tmp/pip-install-pxkdmj8r/openfold_3b67dd159eb04815b2101d5537d3d695
  Running command git rev-parse -q --verify 'sha^4b41059694619831a7db195b7e0988fc4ff3a307'
  Running command git fetch -q https://github.com/aqlaboratory/openfold.git 4b41059694619831a7db195b7e0988fc4ff3a307
  Running command git checkout -q 4b41059694619831a7db195b7e0988fc4ff3a307
  Resolved https://github.com/aqlaboratory/openfold.git to commit 4b41059694619831a7db195b7e0988fc4ff3a307
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: openfold
  Building wheel for openfold (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [289 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-310
      creating build/lib.linux-x86_64-cpython-310/openfold
      copying openfold/config.py -> build/lib.linux-x86_64-cpython-310/openfold
      copying openfold/__init__.py -> build/lib.linux-x86_64-cpython-310/openfold
      creating build/lib.linux-x86_64-cpython-310/openfold/data
      copying openfold/data/templates.py -> build/lib.linux-x86_64-cpython-310/openfold/data
      copying openfold/data/feature_pipeline.py -> build/lib.linux-x86_64-cpython-310/openfold/data
      copying openfold/data/data_modules.py -> build/lib.linux-x86_64-cpython-310/openfold/data
      copying openfold/data/errors.py -> build/lib.linux-x86_64-cpython-310/openfold/data
      copying openfold/data/input_pipeline.py -> build/lib.linux-x86_64-cpython-310/openfold/data
      copying openfold/data/parsers.py -> build/lib.linux-x86_64-cpython-310/openfold/data
      copying openfold/data/data_pipeline.py -> build/lib.linux-x86_64-cpython-310/openfold/data
      copying openfold/data/mmcif_parsing.py -> build/lib.linux-x86_64-cpython-310/openfold/data
      copying openfold/data/data_transforms.py -> build/lib.linux-x86_64-cpython-310/openfold/data
      copying openfold/data/__init__.py -> build/lib.linux-x86_64-cpython-310/openfold/data
      creating build/lib.linux-x86_64-cpython-310/openfold/np
      copying openfold/np/residue_constants.py -> build/lib.linux-x86_64-cpython-310/openfold/np
      copying openfold/np/__init__.py -> build/lib.linux-x86_64-cpython-310/openfold/np
      copying openfold/np/protein.py -> build/lib.linux-x86_64-cpython-310/openfold/np
      creating build/lib.linux-x86_64-cpython-310/openfold/model
      copying openfold/model/template.py -> build/lib.linux-x86_64-cpython-310/openfold/model
      copying openfold/model/primitives.py -> build/lib.linux-x86_64-cpython-310/openfold/model
      copying openfold/model/triangular_multiplicative_update.py -> build/lib.linux-x86_64-cpython-310/openfold/model
      copying openfold/model/embedders.py -> build/lib.linux-x86_64-cpython-310/openfold/model
      copying openfold/model/evoformer.py -> build/lib.linux-x86_64-cpython-310/openfold/model
      copying openfold/model/outer_product_mean.py -> build/lib.linux-x86_64-cpython-310/openfold/model
      copying openfold/model/structure_module.py -> build/lib.linux-x86_64-cpython-310/openfold/model
      copying openfold/model/msa.py -> build/lib.linux-x86_64-cpython-310/openfold/model
      copying openfold/model/model.py -> build/lib.linux-x86_64-cpython-310/openfold/model
      copying openfold/model/triangular_attention.py -> build/lib.linux-x86_64-cpython-310/openfold/model
      copying openfold/model/heads.py -> build/lib.linux-x86_64-cpython-310/openfold/model
      copying openfold/model/torchscript.py -> build/lib.linux-x86_64-cpython-310/openfold/model
      copying openfold/model/dropout.py -> build/lib.linux-x86_64-cpython-310/openfold/model
      copying openfold/model/pair_transition.py -> build/lib.linux-x86_64-cpython-310/openfold/model
      copying openfold/model/__init__.py -> build/lib.linux-x86_64-cpython-310/openfold/model
      creating build/lib.linux-x86_64-cpython-310/openfold/utils
      copying openfold/utils/superimposition.py -> build/lib.linux-x86_64-cpython-310/openfold/utils
      copying openfold/utils/seed.py -> build/lib.linux-x86_64-cpython-310/openfold/utils
      copying openfold/utils/tensor_utils.py -> build/lib.linux-x86_64-cpython-310/openfold/utils
      copying openfold/utils/lr_schedulers.py -> build/lib.linux-x86_64-cpython-310/openfold/utils
      copying openfold/utils/argparse.py -> build/lib.linux-x86_64-cpython-310/openfold/utils
      copying openfold/utils/rigid_utils.py -> build/lib.linux-x86_64-cpython-310/openfold/utils
      copying openfold/utils/loss.py -> build/lib.linux-x86_64-cpython-310/openfold/utils
      copying openfold/utils/logger.py -> build/lib.linux-x86_64-cpython-310/openfold/utils
      copying openfold/utils/trace_utils.py -> build/lib.linux-x86_64-cpython-310/openfold/utils
      copying openfold/utils/feats.py -> build/lib.linux-x86_64-cpython-310/openfold/utils
      copying openfold/utils/callbacks.py -> build/lib.linux-x86_64-cpython-310/openfold/utils
      copying openfold/utils/chunk_utils.py -> build/lib.linux-x86_64-cpython-310/openfold/utils
      copying openfold/utils/validation_metrics.py -> build/lib.linux-x86_64-cpython-310/openfold/utils
      copying openfold/utils/__init__.py -> build/lib.linux-x86_64-cpython-310/openfold/utils
      copying openfold/utils/checkpointing.py -> build/lib.linux-x86_64-cpython-310/openfold/utils
      copying openfold/utils/suppress_output.py -> build/lib.linux-x86_64-cpython-310/openfold/utils
      copying openfold/utils/import_weights.py -> build/lib.linux-x86_64-cpython-310/openfold/utils
      copying openfold/utils/exponential_moving_average.py -> build/lib.linux-x86_64-cpython-310/openfold/utils
      creating build/lib.linux-x86_64-cpython-310/openfold/resources
      copying openfold/resources/__init__.py -> build/lib.linux-x86_64-cpython-310/openfold/resources
      creating build/lib.linux-x86_64-cpython-310/openfold/data/tools
      copying openfold/data/tools/utils.py -> build/lib.linux-x86_64-cpython-310/openfold/data/tools
      copying openfold/data/tools/kalign.py -> build/lib.linux-x86_64-cpython-310/openfold/data/tools
      copying openfold/data/tools/hhblits.py -> build/lib.linux-x86_64-cpython-310/openfold/data/tools
      copying openfold/data/tools/hhsearch.py -> build/lib.linux-x86_64-cpython-310/openfold/data/tools
      copying openfold/data/tools/__init__.py -> build/lib.linux-x86_64-cpython-310/openfold/data/tools
      copying openfold/data/tools/jackhmmer.py -> build/lib.linux-x86_64-cpython-310/openfold/data/tools
      creating build/lib.linux-x86_64-cpython-310/openfold/np/relax
      copying openfold/np/relax/utils.py -> build/lib.linux-x86_64-cpython-310/openfold/np/relax
      copying openfold/np/relax/relax.py -> build/lib.linux-x86_64-cpython-310/openfold/np/relax
      copying openfold/np/relax/cleanup.py -> build/lib.linux-x86_64-cpython-310/openfold/np/relax
      copying openfold/np/relax/amber_minimize.py -> build/lib.linux-x86_64-cpython-310/openfold/np/relax
      copying openfold/np/relax/__init__.py -> build/lib.linux-x86_64-cpython-310/openfold/np/relax
      creating build/lib.linux-x86_64-cpython-310/openfold/utils/kernel
      copying openfold/utils/kernel/attention_core.py -> build/lib.linux-x86_64-cpython-310/openfold/utils/kernel
      copying openfold/utils/kernel/__init__.py -> build/lib.linux-x86_64-cpython-310/openfold/utils/kernel
      running egg_info
      creating openfold.egg-info
      writing openfold.egg-info/PKG-INFO
      writing dependency_links to openfold.egg-info/dependency_links.txt
      writing top-level names to openfold.egg-info/top_level.txt
      writing manifest file 'openfold.egg-info/SOURCES.txt'
      reading manifest file 'openfold.egg-info/SOURCES.txt'
      adding license file 'LICENSE'
      writing manifest file 'openfold.egg-info/SOURCES.txt'
      /home/rekgowr/.local/lib/python3.10/site-packages/setuptools/command/build_py.py:201: _Warning: Package 'openfold.utils.kernel.csrc' is absent from the `packages` configuration.
      !!

              ********************************************************************************
              ############################
              # Package would be ignored #
              ############################
              Python recognizes 'openfold.utils.kernel.csrc' as an importable package[^1],
              but it is absent from setuptools' `packages` configuration.

              This leads to an ambiguous overall configuration. If you want to distribute this
              package, please make sure that 'openfold.utils.kernel.csrc' is explicitly added
              to the `packages` configuration field.

              Alternatively, you can also rely on setuptools' discovery methods
              (for example by using `find_namespace_packages(...)`/`find_namespace:`
              instead of `find_packages(...)`/`find:`).

              You can read more about "package discovery" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

              If you don't want 'openfold.utils.kernel.csrc' to be distributed and are
              already explicitly excluding 'openfold.utils.kernel.csrc' via
              `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
              you can try to use `exclude_package_data`, or `include-package-data=False` in
              combination with a more fine grained `package-data` configuration.

              You can read more about "package data files" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/datafiles.html

              [^1]: For Python, any directory (with suitable naming) can be imported,
                    even if it does not contain any `.py` files.
                    On the other hand, currently there is no concept of package data
                    directory, all directories are treated like packages.
              ********************************************************************************

      !!
        check.warn(importable)
      creating build/lib.linux-x86_64-cpython-310/openfold/utils/kernel/csrc
      copying openfold/utils/kernel/csrc/softmax_cuda_kernel.cu -> build/lib.linux-x86_64-cpython-310/openfold/utils/kernel/csrc
      copying openfold/utils/kernel/csrc/compat.h -> build/lib.linux-x86_64-cpython-310/openfold/utils/kernel/csrc
      copying openfold/utils/kernel/csrc/softmax_cuda.cpp -> build/lib.linux-x86_64-cpython-310/openfold/utils/kernel/csrc
      running build_ext
      /home/rekgowr/.local/lib/python3.10/site-packages/torch/utils/cpp_extension.py:388: UserWarning: The detected CUDA version (11.5) has a minor version mismatch with the version that was used to compile PyTorch (11.7). Most likely this shouldn't be a problem.
        warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
      building 'attn_core_inplace_cuda' extension
      creating /tmp/pip-install-pxkdmj8r/openfold_3b67dd159eb04815b2101d5537d3d695/build/temp.linux-x86_64-cpython-310
      creating /tmp/pip-install-pxkdmj8r/openfold_3b67dd159eb04815b2101d5537d3d695/build/temp.linux-x86_64-cpython-310/openfold
      creating /tmp/pip-install-pxkdmj8r/openfold_3b67dd159eb04815b2101d5537d3d695/build/temp.linux-x86_64-cpython-310/openfold/utils
      creating /tmp/pip-install-pxkdmj8r/openfold_3b67dd159eb04815b2101d5537d3d695/build/temp.linux-x86_64-cpython-310/openfold/utils/kernel
      creating /tmp/pip-install-pxkdmj8r/openfold_3b67dd159eb04815b2101d5537d3d695/build/temp.linux-x86_64-cpython-310/openfold/utils/kernel/csrc
      Emitting ninja build file /tmp/pip-install-pxkdmj8r/openfold_3b67dd159eb04815b2101d5537d3d695/build/temp.linux-x86_64-cpython-310/build.ninja...
      Compiling objects...
      Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
      [1/2] c++ -MMD -MF /tmp/pip-install-pxkdmj8r/openfold_3b67dd159eb04815b2101d5537d3d695/build/temp.linux-x86_64-cpython-310/openfold/utils/kernel/csrc/softmax_cuda.o.d -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/tmp/pip-install-pxkdmj8r/openfold_3b67dd159eb04815b2101d5537d3d695/openfold/utils/kernel/csrc/ -I/home/rekgowr/.local/lib/python3.10/site-packages/torch/include -I/home/rekgowr/.local/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/home/rekgowr/.local/lib/python3.10/site-packages/torch/include/TH -I/home/rekgowr/.local/lib/python3.10/site-packages/torch/include/THC -I/usr/include/python3.10 -c -c /tmp/pip-install-pxkdmj8r/openfold_3b67dd159eb04815b2101d5537d3d695/openfold/utils/kernel/csrc/softmax_cuda.cpp -o /tmp/pip-install-pxkdmj8r/openfold_3b67dd159eb04815b2101d5537d3d695/build/temp.linux-x86_64-cpython-310/openfold/utils/kernel/csrc/softmax_cuda.o -O3 -DVERSION_GE_1_1 -DVERSION_GE_1_3 -DVERSION_GE_1_5 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=attn_core_inplace_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++17
      [2/2] /usr/bin/nvcc  -I/tmp/pip-install-pxkdmj8r/openfold_3b67dd159eb04815b2101d5537d3d695/openfold/utils/kernel/csrc/ -I/home/rekgowr/.local/lib/python3.10/site-packages/torch/include -I/home/rekgowr/.local/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/home/rekgowr/.local/lib/python3.10/site-packages/torch/include/TH -I/home/rekgowr/.local/lib/python3.10/site-packages/torch/include/THC -I/usr/include/python3.10 -c -c /tmp/pip-install-pxkdmj8r/openfold_3b67dd159eb04815b2101d5537d3d695/openfold/utils/kernel/csrc/softmax_cuda_kernel.cu -o /tmp/pip-install-pxkdmj8r/openfold_3b67dd159eb04815b2101d5537d3d695/build/temp.linux-x86_64-cpython-310/openfold/utils/kernel/csrc/softmax_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 --use_fast_math -DVERSION_GE_1_1 -DVERSION_GE_1_3 -DVERSION_GE_1_5 -std=c++14 -maxrregcount=50 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ --expt-relaxed-constexpr --expt-extended-lambda -gencode arch=compute_37,code=sm_37 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_80,code=sm_80 -gencode arch=compute_52,code=sm_52 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=attn_core_inplace_cuda -D_GLIBCXX_USE_CXX11_ABI=0
      FAILED: /tmp/pip-install-pxkdmj8r/openfold_3b67dd159eb04815b2101d5537d3d695/build/temp.linux-x86_64-cpython-310/openfold/utils/kernel/csrc/softmax_cuda_kernel.o
      /usr/bin/nvcc  -I/tmp/pip-install-pxkdmj8r/openfold_3b67dd159eb04815b2101d5537d3d695/openfold/utils/kernel/csrc/ -I/home/rekgowr/.local/lib/python3.10/site-packages/torch/include -I/home/rekgowr/.local/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/home/rekgowr/.local/lib/python3.10/site-packages/torch/include/TH -I/home/rekgowr/.local/lib/python3.10/site-packages/torch/include/THC -I/usr/include/python3.10 -c -c /tmp/pip-install-pxkdmj8r/openfold_3b67dd159eb04815b2101d5537d3d695/openfold/utils/kernel/csrc/softmax_cuda_kernel.cu -o /tmp/pip-install-pxkdmj8r/openfold_3b67dd159eb04815b2101d5537d3d695/build/temp.linux-x86_64-cpython-310/openfold/utils/kernel/csrc/softmax_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 --use_fast_math -DVERSION_GE_1_1 -DVERSION_GE_1_3 -DVERSION_GE_1_5 -std=c++14 -maxrregcount=50 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ --expt-relaxed-constexpr --expt-extended-lambda -gencode arch=compute_37,code=sm_37 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_80,code=sm_80 -gencode arch=compute_52,code=sm_52 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=attn_core_inplace_cuda -D_GLIBCXX_USE_CXX11_ABI=0
      nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
      /home/rekgowr/.local/lib/python3.10/site-packages/torch/include/c10/util/irange.h(54): warning #186-D: pointless comparison of unsigned integer with zero
                detected during:
                  instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator==(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=size_t, one_sided=false, <unnamed>=0]"
      (61): here
                  instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator!=(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=size_t, one_sided=false, <unnamed>=0]"
      /home/rekgowr/.local/lib/python3.10/site-packages/torch/include/c10/core/TensorImpl.h(77): here

      /home/rekgowr/.local/lib/python3.10/site-packages/torch/include/c10/util/irange.h(54): warning #186-D: pointless comparison of unsigned integer with zero
                detected during:
                  instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator==(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=std::size_t, one_sided=true, <unnamed>=0]"
      (61): here
                  instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator!=(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=std::size_t, one_sided=true, <unnamed>=0]"
      /home/rekgowr/.local/lib/python3.10/site-packages/torch/include/ATen/core/qualified_name.h(73): here

      /home/rekgowr/.local/lib/python3.10/site-packages/torch/include/c10/util/irange.h(54): warning #186-D: pointless comparison of unsigned integer with zero
                detected during:
                  instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator==(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=size_t, one_sided=false, <unnamed>=0]"
      (61): here
                  instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator!=(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=size_t, one_sided=false, <unnamed>=0]"
      /home/rekgowr/.local/lib/python3.10/site-packages/torch/include/c10/core/TensorImpl.h(77): here

      /home/rekgowr/.local/lib/python3.10/site-packages/torch/include/c10/util/irange.h(54): warning #186-D: pointless comparison of unsigned integer with zero
                detected during:
                  instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator==(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=std::size_t, one_sided=true, <unnamed>=0]"
      (61): here
                  instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator!=(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=std::size_t, one_sided=true, <unnamed>=0]"
      /home/rekgowr/.local/lib/python3.10/site-packages/torch/include/ATen/core/qualified_name.h(73): here

      /home/rekgowr/.local/lib/python3.10/site-packages/torch/include/c10/util/irange.h(54): warning #186-D: pointless comparison of unsigned integer with zero
                detected during:
                  instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator==(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=size_t, one_sided=false, <unnamed>=0]"
      (61): here
                  instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator!=(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=size_t, one_sided=false, <unnamed>=0]"
      /home/rekgowr/.local/lib/python3.10/site-packages/torch/include/c10/core/TensorImpl.h(77): here

      /home/rekgowr/.local/lib/python3.10/site-packages/torch/include/c10/util/irange.h(54): warning #186-D: pointless comparison of unsigned integer with zero
                detected during:
                  instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator==(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=std::size_t, one_sided=true, <unnamed>=0]"
      (61): here
                  instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator!=(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=std::size_t, one_sided=true, <unnamed>=0]"
      /home/rekgowr/.local/lib/python3.10/site-packages/torch/include/ATen/core/qualified_name.h(73): here

      /home/rekgowr/.local/lib/python3.10/site-packages/torch/include/c10/util/irange.h(54): warning #186-D: pointless comparison of unsigned integer with zero
                detected during:
                  instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator==(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=size_t, one_sided=false, <unnamed>=0]"
      (61): here
                  instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator!=(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=size_t, one_sided=false, <unnamed>=0]"
      /home/rekgowr/.local/lib/python3.10/site-packages/torch/include/c10/core/TensorImpl.h(77): here

      /home/rekgowr/.local/lib/python3.10/site-packages/torch/include/c10/util/irange.h(54): warning #186-D: pointless comparison of unsigned integer with zero
                detected during:
                  instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator==(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=std::size_t, one_sided=true, <unnamed>=0]"
      (61): here
                  instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator!=(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=std::size_t, one_sided=true, <unnamed>=0]"
      /home/rekgowr/.local/lib/python3.10/site-packages/torch/include/ATen/core/qualified_name.h(73): here

      /home/rekgowr/.local/lib/python3.10/site-packages/torch/include/c10/util/irange.h(54): warning #186-D: pointless comparison of unsigned integer with zero
                detected during:
                  instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator==(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=size_t, one_sided=false, <unnamed>=0]"
      (61): here
                  instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator!=(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=size_t, one_sided=false, <unnamed>=0]"
      /home/rekgowr/.local/lib/python3.10/site-packages/torch/include/c10/core/TensorImpl.h(77): here

      /home/rekgowr/.local/lib/python3.10/site-packages/torch/include/c10/util/irange.h(54): warning #186-D: pointless comparison of unsigned integer with zero
                detected during:
                  instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator==(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=std::size_t, one_sided=true, <unnamed>=0]"
      (61): here
                  instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator!=(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=std::size_t, one_sided=true, <unnamed>=0]"
      /home/rekgowr/.local/lib/python3.10/site-packages/torch/include/ATen/core/qualified_name.h(73): here

      /usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’:
        435 |         function(_Functor&& __f)
            |
                                                        ^
      /usr/include/c++/11/bits/std_function.h:435:145: note:         ‘_ArgTypes’
      /usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
        530 |         operator=(_Functor&& __f)
            |
                                                         ^
      /usr/include/c++/11/bits/std_function.h:530:146: note:         ‘_ArgTypes’
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/home/rekgowr/.local/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1893, in _run_ninja_build
          subprocess.run(
        File "/usr/lib/python3.10/subprocess.py", line 524, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-pxkdmj8r/openfold_3b67dd159eb04815b2101d5537d3d695/setup.py", line 74, in <module>
          setup(
        File "/home/rekgowr/.local/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/home/rekgowr/.local/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/rekgowr/.local/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/rekgowr/.local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/rekgowr/.local/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/home/rekgowr/.local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/rekgowr/.local/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 343, in run
          self.run_command("build")
        File "/home/rekgowr/.local/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/rekgowr/.local/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/home/rekgowr/.local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/rekgowr/.local/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/home/rekgowr/.local/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/rekgowr/.local/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/home/rekgowr/.local/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/rekgowr/.local/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/home/rekgowr/.local/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/home/rekgowr/.local/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 843, in build_extensions
          build_ext.build_extensions(self)
        File "/home/rekgowr/.local/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/home/rekgowr/.local/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "/home/rekgowr/.local/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
          _build_ext.build_extension(self, ext)
        File "/home/rekgowr/.local/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
          objects = self.compiler.compile(
        File "/home/rekgowr/.local/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 658, in unix_wrap_ninja_compile
          _write_ninja_file_and_compile_objects(
        File "/home/rekgowr/.local/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1574, in _write_ninja_file_and_compile_objects
          _run_ninja_build(
        File "/home/rekgowr/.local/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1909, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for openfold
  Running setup.py clean for openfold
Failed to build openfold
ERROR: Could not build wheels for openfold, which is required to install pyproject.toml-based projects

I'm very new to this and have less than a month's experience using the terminal - I appreciate that this is likely a simple problem. I have been able to troubleshoot everything else I've done so far using ChatGPT and Github, but this seems like there's something going on within the code I'm importing from you guys and I can't tell what's not compatible at my end unfortunately.

Please advise?

Thanks!

**Comment by susiegriggo** [comment]
I'm having this same issue - any chance you ended up resolving it?

**Comment by Lsz-20** [comment]
The same question

**Comment by Budjavac** [comment]
same error, could this please resolved?

**Comment by lm-jkominek** [comment]
The team was disbanded last year, so there's not gonna be any fixes, unless there's community efforts.
