### ISSUE TITLE
Sample source for ESM metagenomic atlas records

### ISSUE THREAD

**Issue by ntnn19** [facebookresearch/esm#593]
Hello,

I am trying to get some metadata on some entries. I am particularly interested in information about the source of the sequences (e.g. marine, soil, etc.). I tried to get these data by searching for some ESM metagenomic atlas identifiers/sequences in EBI MGnify and BLAST, but could not obtain any exact matches.

Could you please help me to find this information?

Thanks in advance

**Comment by naailkhan28** [comment]
The process for this isn't exactly trivial but I've done it before. You need to go to the [MGnify Protein Database](http://ftp.ebi.ac.uk/pub/databases/metagenomics/peptide_database/current_release/) and retrieve MGYC and ERZ accessions for your MGYP protein accessions. You can use these to get MGYA analysis accessions from the MGnify API, and then you can use a combination of these to query the MGnify API or the European Nucleotide Archive to get sample metadata
