### ISSUE TITLE
Adding the embedders to bio_embeddings

### ISSUE THREAD

**Issue by sacdallago** [facebookresearch/esm#6]
Hey folks :)

Great work!. As I mentioned on Twitter, it'd be nice to add your models to [bio_embeddings](https://github.com/sacdallago/bio_embeddings). Purpose of the pipeline: make it easy for less-tech-savy bio/informatician to use protein LMs. Since you use torch, this should be quite straightforward since [we already have some transformer models](https://github.com/sacdallago/bio_embeddings/tree/develop/bio_embeddings/embed).

Out of the box, you get the whole "read FASTA in, make run reproducible", project, viz & embedding annotation transfer ([goPredSim](https://doi.org/10.1101/2020.09.04.282814)) pipelines. **Edit**: oh, and the auto-batching of large sequence files between GPU/CPU (which is not at all intuitive for the avg user), + per-sequence vs per-AA representations (looking through closed issues, #2 )

I noticed you have [some variant prediction code](https://github.com/facebookresearch/esm/blob/master/examples/variant_prediction.ipynb), maybe it makes sense to include that as a pipeline step if it is sensible? 

I'll link this to our issue for integration so that we can cross-follow the status: https://github.com/sacdallago/bio_embeddings/issues/62

**Comment by tomsercu** [comment]
Thanks Chrstian, We'll be happy to work with you folks to make this happen! The team is a bit swamped right now, but will look into this soon!

**Comment by konstin** [comment]
I've added ESM to bio_embeddings: https://github.com/sacdallago/bio_embeddings/blob/0b7d5f32ec7743b5fbdfcbede5bf2f0e1cbdb52b/bio_embeddings/embed/esm_embedder.py. It would be great if you could check whether the implementation looks correct to you.

Could publish ESM on pypi? I've seen that you have a proper python package (thanks for that!) and [could verify with testpypi](https://test.pypi.org/project/esm/0.1.0/#files) that `python setup.py sdist bdist_wheel && pip instal twine && twine upload dist/*` works.

**Comment by sacdallago** [comment]
Also: @tomsercu is your blog's gmail address still the best one to reach you? :) I sent you something ~2 days ago, just wondering :)

**Comment by sacdallago** [comment]
I think this is pretty much done, except we'll now also add the new model :P Congrats on that one, too.
