### ISSUE TITLE
ModuleNotFoundError: fused_layer_norm_cuda

### ISSUE THREAD

**Issue by SimonKitSangChu** [facebookresearch/esm#62]
Following the QuickStart instruction, I load the model through PyTorch Hub.
```
model, alphabet = torch.hub.load("facebookresearch/esm", "esm1b_t33_650M_UR50S")
```

Exception experienced:
```
ModuleNotFoundError: No module named 'fused_layer_norm_cuda'
```

Double checked `torch.__version__` as `1.7.0`. Can provide more info if needed.

**Comment by tomsercu** [comment]
Sounds like an issue with your nvidia apex install; if it's not installed we'll [fall back on default layernorm](https://github.com/facebookresearch/esm/blob/master/esm/modules.py#L65-L77).
So you can check if you can either (a) uninstall apex or (b) any of these solutions work for you:
https://github.com/NVIDIA/apex/issues/161
https://github.com/NVIDIA/apex/issues/954
