### ISSUE TITLE
ESMFold API SSL Ceritifcate Error

### ISSUE THREAD

**Issue by falatfernando** [facebookresearch/esm#634]
I have a python application that uses ESMFold API to return the protein 3D structure. A few days ago my app stopped runing pointing a SSL Ceriticate error:

 SSL Certificate Error: requests.exceptions.SSLError: HTTPSConnectionPool(host='api.esmatlas.com', port=443): Max retries exceeded with url: /foldSequence/v1/pdb/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)'))).
 
Do we now need to implement a ESMFold API SSL Certificate in code/repository or this is a bug with python? Can't find anything about API policy changes.

Thanks in advance.

**Comment by StephaneRedon** [comment]
This seems to be related to https://github.com/facebookresearch/esm/discussions/627

**Comment by falatfernando** [comment]
Managed to disable SSL certificate check and the API seems to be working fine in native apps.
