### ISSUE TITLE
Version the lib

### ISSUE THREAD

**Issue by hadim** [facebookresearch/esm#7]
Would that be possible to add a git tag to the repo and so version the lib so we can make a package of it on conda-forge or similar?

**Comment by hadim** [comment]
ping @tomsercu

**Comment by tomsercu** [comment]
@hadim thanks for your interest - I added the tag v0.1.0 (also in `esm/version.py`).
Let me know if any issue!

**Comment by hadim** [comment]
Thanks! Not sure if I'll make a conda package of esm since it can also be loaded with `torch.hub` but at least having a git tag is a good practice.
