### ISSUE TITLE
[Question] Supervised contact map and secondary structure models

### ISSUE THREAD

**Issue by flajolet** [facebookresearch/esm#90]
Hello,

Are you planning on releasing the model (architecture and weights) that you have trained in a supervised fashion for predicting contact maps and secondary structure in "Biological structure and function emerge from scaling unsupervised learning to 250 million protein sequences"?

Thank you for making all this awesome work available!

**Comment by tomsercu** [comment]
Hi, thanks for the kind words! We want to release those supervised models along with large parts of our internal research codebase, but have no clarity on the timeline for this yet. Definitely at least half a year out.
