### ISSUE TITLE
Documentation needed: contact prediction distance threshold

### ISSUE THREAD

**Issue by javierbq** [facebookresearch/esm#94]
In the jupyter notebook example of [contact-prediction using the MSA transformer] (https://github.com/facebookresearch/esm/blob/0097c27290c7c88c4bc0fc4df3692d2c23a6aa54/examples/contact_prediction.ipynb) there is no mention to the threshold use to define a contact.

**Comment by tomsercu** [comment]
Hi Javier, thanks for your interest!
What exactly is the question / concern?
The model outputs continuous valued probabilities per pair of positions.
One can threshold at 50% or any other threshold, or the typical contact precision metrics only considers for example the top-L values.

**Comment by tomsercu** [comment]
This is now added as a comment in https://github.com/facebookresearch/esm/blob/master/examples/contact_prediction.ipynb
